//*************************************************************************************
// Name             : CaseProcessingTest
// Description      : Class to increase test coverage of "CaseProcessing"
// Created By       : Nilanjana Mukherjee
// Created Date     : 06/22/2015
//TestCoverage      : 81%
//TestCoverage      : 81 %
// ************************************************************************************
@isTest(seealldata=true)
private class CaseProcessingTest
{ 
        public CaseProcessingTest(){
                
                //Updating from git
        }
        
}
